FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY ./ ./
WORKDIR /app/FastTechFoods

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
COPY --from=build /app/FastTechFoods/out .

ENV ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:8080

EXPOSE 8080


ENTRYPOINT ["dotnet", "Api.dll"]
